### PR TITLE
Style login pages

### PR DESCRIPTION
**Pull request by mermop**
Use the Bootstrap classes to make login pages look a little bit nicer.

<details>
<summary>Screenshots</summary>

Screen Shot 2019-06-13 at 12 06 26 PM
Screen Shot 2019-06-13 at 12 06 30 PM
Screen Shot 2019-06-13 at 12 06 41 PM

</details>

### CODE REVIEW

**Comment by mermop** [comment]
Ah - this can be replaced with `bootstrap_form_for` after #47, as it adds the `bootstrap_form` gem

**Comment by mermop** [comment]
Now using `bootstrap_form_for`

**Comment by mermop** [comment]
@Br3nda can you please approve the Percy screenshots?

**Comment by lamorrison** [comment]
please remove `logfile`

**Pull request merged**
